In [4]:
import numpy as np

In [6]:
#1 d array
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arr1)

numpy.ndarray

In [9]:
print(arr1.ndim)

1


In [11]:
print(arr1.ndim)

1


In [12]:
type(arr1)

numpy.ndarray

In [13]:
arr1

array([1, 2, 3, 4, 5, 6])

In [14]:
arr1

array([1, 2, 3, 4, 5, 6])

In [16]:
arr2=np.array(([1,2,3],[4,5,6]))
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(arr2)

numpy.ndarray

In [18]:
print(arr2.ndim)

2


In [19]:
arr3=np.array((3,2))

array([3, 2])

In [20]:
arr=np.array(34)
arr

array(34)

In [21]:
arr.ndim

0

In [22]:
type(arr)

numpy.ndarray

In [23]:
arr3=np.zeros((4,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
arr3.ndim

2

In [26]:
arr4.ndim

2