In [2]:
  pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
# 1-d array
arrl=np.array([1,2,3,4,5])

In [6]:
arrl

array([1, 2, 3, 4, 5])

In [7]:
type(arrl)

numpy.ndarray

In [8]:
print(arrl.ndim)

1


In [9]:
#2-d Array
arr2=np.array([[1,2,3,],[4,5,6]])

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(arr2.ndim)

2


In [12]:
#0-d Array
arr=np.array(55)
arr

array(55)

In [13]:
arr.ndim

0

In [14]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
print(arr3.ndim)

2


In [16]:
type(arr3)

numpy.ndarray

In [17]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
# aceessing Array Element
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [3]:
arr1[4]

np.int64(5)

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2[0,1]

np.int64(2)

In [6]:
arr2[1]

array([4, 5, 6])

In [7]:
arr2[1,1]

np.int64(5)

In [8]:
arr2[1,2]

np.int64(6)

In [9]:
import numpy as np
arr3 = np.array([1,2,3,4,5,6,7])
print (arr3[1:5])

[2 3 4 5]


In [10]:
arr4=np.array([1,2,3,4,5,6,7])
print(arr4[5:])

[6 7]


In [11]:
arr5=np.array([1,2,3,4,5,6,7])
print(arr5[:4])

[1 2 3 4]


In [12]:
arr6=np.array([1,2,3,4,5,6,7])
print(arr6[-3:-1])


[5 6]


In [14]:
arr7=np.array([1,2,3,4,5,6,7])
print(arr7[1:5:2])

[2 4]


In [15]:
arr=np.array([[1,2,3,4],[5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [3]:
#reshape from 1d to 2d
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
#reshape from 1d to 3d
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [6]:
# Iterate on the elements of the following 2-d array:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [7]:
# numpy joining array
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [10]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [2]:
# spliting numpy arrays
#spliting is reverse operation of joining.
import numpy as np
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [3]:
# Random Numbers
# generate a random integer  from 0 to 100.
import numpy as np
from numpy import random
x = random.randint(100)
print(x)

9


In [4]:
# random modules rand() method returns a random floiat between 0 and1.
x = random.rand()
print(x)

0.47206609781730435


In [7]:
# generate random array
x = random.randint(100, size=(5))
print(x)

[ 6  2 12 48 64]


In [8]:
# a 2d array with 3 rows, each row containing 5 random integeres from 0 to 100:
x = random.randint(100,size=(3,5))
print(x)

[[46 15 58 75 20]
 [51 51 72 39 83]
 [32 38 98 90  4]]


In [9]:
# generate a 1d  array containing 5 random floats:
x = random.rand(5)
print(x)

[0.047936   0.35073136 0.02125157 0.36387777 0.83653517]


In [12]:
# generate a 2 d array with 3 rows , each row cotaing  5 random umber
x = random.rand(3,5)
print(x)

[[0.64274414 0.07649936 0.50304173 0.54780897 0.52987155]
 [0.26004407 0.54780652 0.53304376 0.54662077 0.00943436]
 [0.75816124 0.00436427 0.94058798 0.98848643 0.09589222]]


In [13]:
# searching array 
arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [14]:
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [15]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [16]:
arr = np.array(["banana","cherry","apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [17]:
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
